version: '3.7'

services:

  prometheus:
    container_name: prometheus
    image: "prom/prometheus"
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/datasources/:/etc/grafana/provisioning/datasources/
      - ./docker/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards



  cassandra-extractor:
    image: busybox:latest
    container_name: cassandra-extractor
    volumes:
      - ./docker/cassandra_exporter/datastax-mcac-agent-0.3.5.tar.gz:/opt/datastax-mcac-agent-0.3.5.tar.gz
      - cassandra_mcac:/opt/datastax-mcac-agent-0.3.5
    command: sh -c "tar -xzf /opt/datastax-mcac-agent-0.3.5.tar.gz -C /opt/"


  cassandra0:
    image: cassandra:4.0.12
    container_name: cassandra0
    hostname: cassandra0
    networks:
      - cassandra
    environment: &environment
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-javaagent:/opt/datastax-mcac-agent-0.3.5/lib/datastax-mcac-agent.jar
      - CASSANDRA_SEEDS=cassandra0,cassandra1
      - CASSANDRA_CLUSTER_NAME=MyTestCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
    ports:
      - "9042:9042"
      - "9103:9103"
    volumes:
      - cassandra_mcac:/opt/datastax-mcac-agent-0.3.5
    depends_on:
      cassandra-extractor:
        condition: service_completed_successfully

    deploy: &deploy
      resources:
        limits:
          cpus: '4'

  cassandra1:
    image: cassandra:4.0.12
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra
    ports:
      - "9043:9042"
      - "9104:9103"
    environment: *environment
    volumes:
      - cassandra_mcac:/opt/datastax-mcac-agent-0.3.5
    depends_on:
      cassandra0:
        condition: service_started
      cassandra-extractor:
        condition: service_completed_successfully
    deploy: *deploy


  cassandra2:
    image: cassandra:4.0.12
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra
    ports:
      - "9044:9042"
      - "9105:9103"
    environment: *environment
    volumes:
      - cassandra_mcac:/opt/datastax-mcac-agent-0.3.5
    depends_on:
      cassandra0:
        condition: service_started
      cassandra-extractor:
        condition: service_completed_successfully
    deploy: *deploy

  cassandra3:
    image: cassandra:4.0.12
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra
    ports:
      - "9045:9042"
      - "9106:9103"
    environment: *environment
    volumes:
      - cassandra_mcac:/opt/datastax-mcac-agent-0.3.5
    depends_on:
      cassandra1:
        condition: service_started
      cassandra-extractor:
        condition: service_completed_successfully
    deploy: *deploy

networks:
  cassandra:

volumes:
  cassandra_mcac: