# @no-redirect
# @no-cookie-jar
POST http://localhost:8080/api/v1/message
Content-Type: application/json

{
  "conversationId": 1,
  "senderId": 1,
  "messageText": "{{$random.alphanumeric(100)}}"
}


### Send GET request
GET http://localhost:8080/api/v1/message/1
