version: '3.7'

services:


  hicha:
    image: hicha-app:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mariadb://mariadb:3306/hicha?user=myuser&password=secret
