spring:
  application:
    name: hicha-business
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true


