spring:
  application:
    name: hicha-business
  sql:
    init:
      mode: always

  cassandra:
    schema-action: create_if_not_exists
    request:
      timeout: 60s
    connection:
      connect-timeout: 60s
      init-query-timeout: 60s
    keyspace-name: hicha


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true
#logging:
#  level:
#    root: info

