global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'hicha-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb-exporter:9104']

  - job_name: 'cassandra'
    static_configs:
      - targets: [ 'cassandra0:9103', 'cassandra1:9103', 'cassandra2:9103', 'cassandra3:9103' ]

